// Generates src/generated/abis.ts from Foundry artifacts (contracts/out). Run after `forge build`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "contracts", "out");
const contracts = [
  ["CreditPool", "CreditPool.sol"],
  ["Tranche", "Tranche.sol"],
  ["EpochRedemptions", "EpochRedemptions.sol"],
  ["FirstLossVault", "FirstLossVault.sol"],
  ["InvoiceNFT", "InvoiceNFT.sol"],
  ["PoolFactory", "PoolFactory.sol"],
  ["PoolLens", "PoolLens.sol"],
  ["ComplianceRegistry", "ComplianceRegistry.sol"],
  ["Underwriting", "Underwriting.sol"],
  ["DefaultManager", "DefaultManager.sol"],
  ["FeeCollector", "FeeCollector.sol"],
  ["ProjectTokenHooks", "ProjectTokenHooks.sol"],
];
let src = "// AUTO-GENERATED by scripts/gen-abis.mjs from contracts/out. Do not edit.\n\n";
for (const [name, file] of contracts) {
  const abi = JSON.parse(readFileSync(join(out, file, `${name}.json`), "utf8")).abi;
  src += `export const ${name[0].toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(here, "..", "src", "generated", "abis.ts"), src);
console.log(`wrote ${contracts.length} ABIs`);
